# Generated by Django 4.2.2 on 2023-06-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinApp', '0007_alter_customuser_username'),
    ]

    operations = [
    ]
