# Generated by Django 4.2.2 on 2023-06-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinApp', '0008_auto_20230621_1425'),
    ]

    operations = [
    ]
